create table if not exists public.camp_rise_again_site_settings (
  id integer primary key default 1 check (id = 1),
  announcement text not null default '',
  hero_lead text not null default '',
  about_heading text not null default '',
  fall_details text not null default '',
  spring_details text not null default '',
  contact_heading text not null default '',
  contact_copy text not null default '',
  updated_at timestamptz not null default now()
);

insert into public.camp_rise_again_site_settings (
  id, hero_lead, about_heading, fall_details, spring_details, contact_heading, contact_copy
) values (
  1,
  'Camp Rise Again is an adult camp created for individuals who are currently struggling with depression and may be feeling isolated, overwhelmed, hopeless, or disconnected from life.',
  'A safe, supportive place to reconnect with life and with others.',
  'Fall camp details, dates, location, and capacity will be added here.',
  'Spring camp details, dates, location, and capacity will be added here.',
  'Questions before you apply?',
  'Send us a message and your email app will open with your answers already included so you can review and send it directly.'
) on conflict (id) do nothing;

create table if not exists public.camp_rise_again_schedule (
  id bigint generated by default as identity primary key,
  day_label text not null default 'Day 1',
  time_label text not null default '',
  title text not null,
  details text not null default '',
  sort_order integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
