create table if not exists public.camp_rise_again_resources (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  href text not null,
  action_label text not null default 'Learn More',
  category text not null default 'Support resource',
  is_active boolean not null default true,
  sort_order integer not null default 10,
  created_at timestamptz not null default now()
);

alter table public.camp_rise_again_resources enable row level security;

grant select on table public.camp_rise_again_resources to anon, authenticated;
grant insert, update, delete on table public.camp_rise_again_resources to authenticated;
grant usage, select on sequence public.camp_rise_again_resources_id_seq to authenticated;

drop policy if exists "camp resources public read" on public.camp_rise_again_resources;
create policy "camp resources public read"
on public.camp_rise_again_resources
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "camp resources admin read" on public.camp_rise_again_resources;
create policy "camp resources admin read"
on public.camp_rise_again_resources
for select
to authenticated
using (
  lower(auth.jwt() ->> 'email') = any (
    array['schofieldtierra@gmail.com','zanibethel@gmail.com']
  )
);

drop policy if exists "camp resources admin insert" on public.camp_rise_again_resources;
create policy "camp resources admin insert"
on public.camp_rise_again_resources
for insert
to authenticated
with check (
  lower(auth.jwt() ->> 'email') = any (
    array['schofieldtierra@gmail.com','zanibethel@gmail.com']
  )
);

drop policy if exists "camp resources admin update" on public.camp_rise_again_resources;
create policy "camp resources admin update"
on public.camp_rise_again_resources
for update
to authenticated
using (
  lower(auth.jwt() ->> 'email') = any (
    array['schofieldtierra@gmail.com','zanibethel@gmail.com']
  )
)
with check (
  lower(auth.jwt() ->> 'email') = any (
    array['schofieldtierra@gmail.com','zanibethel@gmail.com']
  )
);

drop policy if exists "camp resources admin delete" on public.camp_rise_again_resources;
create policy "camp resources admin delete"
on public.camp_rise_again_resources
for delete
to authenticated
using (
  lower(auth.jwt() ->> 'email') = any (
    array['schofieldtierra@gmail.com','zanibethel@gmail.com']
  )
);

insert into public.camp_rise_again_resources (
  title, description, href, action_label, category, is_active, sort_order
)
select * from (values
  (
    '988 Suicide & Crisis Lifeline',
    'If you are in emotional distress, having thoughts of suicide, or need someone to talk with, call or text 988. Support is available 24/7 in the United States.',
    'https://988lifeline.org/',
    'Visit 988 Lifeline',
    'Crisis support',
    true,
    10
  ),
  (
    'SAMHSA National Helpline',
    'Free, confidential treatment referral and information for mental health and substance use concerns. Call 1-800-662-HELP (4357), 24 hours a day, 365 days a year.',
    'https://www.samhsa.gov/find-help/helplines/national-helpline',
    'Visit SAMHSA',
    'Treatment & referrals',
    true,
    20
  ),
  (
    'FindTreatment.gov',
    'Search for mental health and substance use treatment providers near you using SAMHSA''s confidential treatment locator.',
    'https://findtreatment.gov/',
    'Find Treatment',
    'Treatment & referrals',
    true,
    30
  ),
  (
    'NAMI HelpLine',
    'Get mental health information, resource referrals, and peer-informed support from the National Alliance on Mental Illness.',
    'https://www.nami.org/nami-helpline/',
    'Visit NAMI',
    'Community support',
    true,
    40
  ),
  (
    'Find Your Local NAMI',
    'Connect with a NAMI organization near you for local programs, support groups, education, and community resources.',
    'https://www.nami.org/find-your-local-nami/',
    'Find Local Support',
    'Community support',
    true,
    50
  )
) as seed(title, description, href, action_label, category, is_active, sort_order)
where not exists (select 1 from public.camp_rise_again_resources);
