create table if not exists public.camp_rise_again_team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  bio text not null default '',
  image_path text not null default '',
  is_visible boolean not null default true,
  sort_order integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.camp_rise_again_team_members enable row level security;

drop policy if exists "camp team public read" on public.camp_rise_again_team_members;
create policy "camp team public read"
on public.camp_rise_again_team_members
for select
to anon, authenticated
using (
  is_visible = true
  or lower(coalesce((select auth.jwt()->>'email'), ''))
    in ('schofieldtierra@gmail.com','zanibethel@gmail.com')
);

drop policy if exists "camp team admin write" on public.camp_rise_again_team_members;
create policy "camp team admin write"
on public.camp_rise_again_team_members
for all
to authenticated
using (
  lower(coalesce((select auth.jwt()->>'email'), ''))
    in ('schofieldtierra@gmail.com','zanibethel@gmail.com')
)
with check (
  lower(coalesce((select auth.jwt()->>'email'), ''))
    in ('schofieldtierra@gmail.com','zanibethel@gmail.com')
);

grant select on public.camp_rise_again_team_members to anon, authenticated;
grant insert, update, delete on public.camp_rise_again_team_members to authenticated;
grant usage, select on sequence public.camp_rise_again_team_members_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'camp-rise-again-team',
  'camp-rise-again-team',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
set public = true,
    file_size_limit = 5242880,
    allowed_mime_types = array['image/jpeg','image/png','image/webp'];

drop policy if exists "camp team admin upload" on storage.objects;
create policy "camp team admin upload"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'camp-rise-again-team'
  and lower(coalesce((select auth.jwt()->>'email'), ''))
    in ('schofieldtierra@gmail.com','zanibethel@gmail.com')
);

drop policy if exists "camp team admin update images" on storage.objects;
create policy "camp team admin update images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'camp-rise-again-team'
  and lower(coalesce((select auth.jwt()->>'email'), ''))
    in ('schofieldtierra@gmail.com','zanibethel@gmail.com')
)
with check (
  bucket_id = 'camp-rise-again-team'
  and lower(coalesce((select auth.jwt()->>'email'), ''))
    in ('schofieldtierra@gmail.com','zanibethel@gmail.com')
);

drop policy if exists "camp team admin delete images" on storage.objects;
create policy "camp team admin delete images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'camp-rise-again-team'
  and lower(coalesce((select auth.jwt()->>'email'), ''))
    in ('schofieldtierra@gmail.com','zanibethel@gmail.com')
);
